23 create transaction object schema
mbrewer05/csc307-team3project pull request #33
Opened 2021-05-19 03:48 UTC by mbrewer05

2021-05-19 15:06 UTC, ghost approved these changes

2021-05-20 18:06 UTC, ghuarng requested changes
Minor type errors in transaction.json and user.json

2021-05-20 18:06 UTC, ghuarng commented on .gitignore
> +backend/flaskMongo.pyc
Use this instead of old code to resolve merge conflict

2021-05-20 18:06 UTC, ghuarng commented on backend/models/transaction.json
> +    "value": signed_int,
Resolve type error

2021-05-20 18:06 UTC, ghuarng commented on backend/models/user.json
> +    "budget": int,
Resolve type errors

2021-05-20 18:18 UTC, ghuarng approved these changes

2021-05-20 18:59 UTC, cpshan approved these changes
Looks good to me

2021-05-20 19:04 UTC, merged

2021-05-27 23:00 UTC, elei02 commented
LGTM

2021-06-02 05:03 UTC, mbrewer05 reviewed
LGTM